# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5ee9d59198aec61de43d8504f44ef633da98f11c48de02f716d16dea26b2758f1f9849b3655978549524ecb50779f0e5646c7fbca4548db8ef52b780017c5bd

test:
  secret_key_base: 5d5d66ae0f71a049bc610096a371161aa6a15bbe663c7b4234b04caf3a7ea5ccaffa821dfde039fb3aae138c1bf15c0f341503cc69f78eeaa5044d8b543fd549

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
