# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7a60de07d066525a5274014cfef2fe81a3803079546af43fa6f812f178b1f37d65d1e2f7f8d02d7f61efe0da223810e78a2a67f3841787192917e622891edf2

test:
  secret_key_base: 97f3a1517536fc24c1395ca57f935848d78a5704bccadc79ce1d56840bccc4df192821a8562ba89151f02327672be53a6f9c2f56be6a8076d2f8b393fc9f9e76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
